"""empty message

Revision ID: 1b1d0dc799c5
Revises: b63ff0e0b2da
Create Date: 2026-02-28 14:16:48.286248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1d0dc799c5'
down_revision: Union[str, Sequence[str], None] = 'b63ff0e0b2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.String(length=128), nullable=False))
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('books', 'author')
    # ### end Alembic commands ###
