"""empty message

Revision ID: b63ff0e0b2da
Revises: 838b84f9735f
Create Date: 2026-02-28 14:15:24.530778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63ff0e0b2da'
down_revision: Union[str, Sequence[str], None] = '838b84f9735f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('external_id', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_books_external_id'), 'books', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_external_id'), table_name='books')
    op.drop_column('books', 'external_id')
    # ### end Alembic commands ###
